language: python
python:
  - "2.7"
env:
  - DJANGO=1.7.7
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install coveralls
script:
  - coverage run --source=example_project setup.py test
after_success:
  - coveralls --exclude manage.py --exclude example_project
