language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION>=1.7.7
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install coveralls
script:
  - coverage run --source=example_project setup.py test
after_success:
  - coveralls
